/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace LibAsset {
  export type AssetStruct = {
    assetClass: BytesLike;
    data: BytesLike;
    value: BigNumberish;
  };

  export type AssetStructOutput = [string, string, BigNumber] & {
    assetClass: string;
    data: string;
    value: BigNumber;
  };
}

export interface NaaSExchangeInterface extends utils.Interface {
  functions: {
    "EIP_1271_MAGICVALUE()": FunctionFragment;
    "approveOrderHash_(bytes32)": FunctionFragment;
    "approveOrder_(address,address,address,bytes4,bytes,uint256,uint256,uint256,uint256,bool)": FunctionFragment;
    "approved(address,bytes32)": FunctionFragment;
    "atomicMatch_(uint256[16],bytes4[2],bytes,bytes,bytes,bytes,uint8[2],bytes32,bytes)": FunctionFragment;
    "codename()": FunctionFragment;
    "defaultProtocolFee()": FunctionFragment;
    "feeAggregator()": FunctionFragment;
    "fills(address,bytes32)": FunctionFragment;
    "hashOrder_(address,address,address,bytes4,bytes,uint256,uint256,uint256,uint256)": FunctionFragment;
    "initOwner(address)": FunctionFragment;
    "initialize(address[],address,address,address)": FunctionFragment;
    "name()": FunctionFragment;
    "owner()": FunctionFragment;
    "protocolFeeReceivers(address)": FunctionFragment;
    "psiFee()": FunctionFragment;
    "registries(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "royaltiesRegistry()": FunctionFragment;
    "setDefaultProtocolFee(uint256,address)": FunctionFragment;
    "setOrderFill_(bytes32,uint256)": FunctionFragment;
    "setProtocolFeeForToken(address,uint256,address)": FunctionFragment;
    "setRegistry(address,bool)": FunctionFragment;
    "setRoyaltiesRegistry(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferWithFees(address,address,address,(bytes4,bytes,uint256),(bytes4,bytes,uint256),bytes,bytes)": FunctionFragment;
    "validateOrderAuthorization_(bytes32,address,bytes)": FunctionFragment;
    "validateOrderParameters_(address,address,address,bytes4,bytes,uint256,uint256,uint256,uint256)": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "EIP_1271_MAGICVALUE"
      | "approveOrderHash_"
      | "approveOrder_"
      | "approved"
      | "atomicMatch_"
      | "codename"
      | "defaultProtocolFee"
      | "feeAggregator"
      | "fills"
      | "hashOrder_"
      | "initOwner"
      | "initialize"
      | "name"
      | "owner"
      | "protocolFeeReceivers"
      | "psiFee"
      | "registries"
      | "renounceOwnership"
      | "royaltiesRegistry"
      | "setDefaultProtocolFee"
      | "setOrderFill_"
      | "setProtocolFeeForToken"
      | "setRegistry"
      | "setRoyaltiesRegistry"
      | "transferOwnership"
      | "transferWithFees"
      | "validateOrderAuthorization_"
      | "validateOrderParameters_"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "EIP_1271_MAGICVALUE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveOrderHash_",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveOrder_",
    values: [
      string,
      string,
      string,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "approved",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "atomicMatch_",
    values: [
      BigNumberish[],
      [BytesLike, BytesLike],
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      [BigNumberish, BigNumberish],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "codename", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "defaultProtocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeAggregator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fills",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashOrder_",
    values: [
      string,
      string,
      string,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "initOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string[], string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeReceivers",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "psiFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "registries", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltiesRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultProtocolFee",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setOrderFill_",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeForToken",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistry",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoyaltiesRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferWithFees",
    values: [
      string,
      string,
      string,
      LibAsset.AssetStruct,
      LibAsset.AssetStruct,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOrderAuthorization_",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateOrderParameters_",
    values: [
      string,
      string,
      string,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "EIP_1271_MAGICVALUE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveOrderHash_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveOrder_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approved", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "atomicMatch_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "codename", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeAggregator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fills", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hashOrder_", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeReceivers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "psiFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltiesRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrderFill_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRoyaltiesRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferWithFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOrderAuthorization_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateOrderParameters_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "OrderApproved(bytes32,address,address,address,bytes4,bytes,uint256,uint256,uint256,uint256,bool)": EventFragment;
    "OrderFillChanged(bytes32,address,uint256)": EventFragment;
    "OrdersMatched(bytes32,bytes32,address,address,uint256,uint256,bytes32)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Transfer(tuple,address,address,bytes4,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OrderApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OrderFillChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OrdersMatched"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export interface OrderApprovedEventObject {
  hash: string;
  registry: string;
  maker: string;
  staticTarget: string;
  staticSelector: string;
  staticExtradata: string;
  maximumFill: BigNumber;
  listingTime: BigNumber;
  expirationTime: BigNumber;
  salt: BigNumber;
  orderbookInclusionDesired: boolean;
}
export type OrderApprovedEvent = TypedEvent<
  [
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean
  ],
  OrderApprovedEventObject
>;

export type OrderApprovedEventFilter = TypedEventFilter<OrderApprovedEvent>;

export interface OrderFillChangedEventObject {
  hash: string;
  maker: string;
  newFill: BigNumber;
}
export type OrderFillChangedEvent = TypedEvent<
  [string, string, BigNumber],
  OrderFillChangedEventObject
>;

export type OrderFillChangedEventFilter =
  TypedEventFilter<OrderFillChangedEvent>;

export interface OrdersMatchedEventObject {
  firstHash: string;
  secondHash: string;
  firstMaker: string;
  secondMaker: string;
  newFirstFill: BigNumber;
  newSecondFill: BigNumber;
  metadata: string;
}
export type OrdersMatchedEvent = TypedEvent<
  [string, string, string, string, BigNumber, BigNumber, string],
  OrdersMatchedEventObject
>;

export type OrdersMatchedEventFilter = TypedEventFilter<OrdersMatchedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TransferEventObject {
  asset: LibAsset.AssetStructOutput;
  from: string;
  to: string;
  transferType: string;
  assetExtraData: string;
}
export type TransferEvent = TypedEvent<
  [LibAsset.AssetStructOutput, string, string, string, string],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface NaaSExchange extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NaaSExchangeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    EIP_1271_MAGICVALUE(overrides?: CallOverrides): Promise<[string]>;

    approveOrderHash_(
      hash_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    approveOrder_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      orderbookInclusionDesired: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    approved(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    atomicMatch_(
      uints: BigNumberish[],
      staticSelectors: [BytesLike, BytesLike],
      firstExtradata: BytesLike,
      firstCalldata: BytesLike,
      secondExtradata: BytesLike,
      secondCalldata: BytesLike,
      howToCalls: [BigNumberish, BigNumberish],
      metadata: BytesLike,
      signatures: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    codename(overrides?: CallOverrides): Promise<[string]>;

    defaultProtocolFee(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { fee: BigNumber; target: string }>;

    feeAggregator(overrides?: CallOverrides): Promise<[string]>;

    fills(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    hashOrder_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { hash: string }>;

    initOwner(
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      registryAddrs: string[],
      protocolFeeReceiver: string,
      _feeAggregator: string,
      _royaltiesRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    protocolFeeReceivers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { fee: BigNumber; target: string }>;

    psiFee(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { fee: BigNumber; target: string }>;

    registries(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    royaltiesRegistry(overrides?: CallOverrides): Promise<[string]>;

    setDefaultProtocolFee(
      protocolFee: BigNumberish,
      protocolFeeReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOrderFill_(
      hash_: BytesLike,
      fill: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setProtocolFeeForToken(
      token: string,
      protocolFee: BigNumberish,
      protocolFeeReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRegistry(
      registryAddrs: string,
      enabled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRoyaltiesRegistry(
      newRoyaltiesRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferWithFees(
      registry: string,
      from: string,
      to: string,
      asset: LibAsset.AssetStruct,
      counterAsset: LibAsset.AssetStruct,
      assetExtraData: BytesLike,
      arg6: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validateOrderAuthorization_(
      hash_: BytesLike,
      maker: string,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    validateOrderParameters_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    version(overrides?: CallOverrides): Promise<[string]>;
  };

  EIP_1271_MAGICVALUE(overrides?: CallOverrides): Promise<string>;

  approveOrderHash_(
    hash_: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  approveOrder_(
    registry: string,
    maker: string,
    staticTarget: string,
    staticSelector: BytesLike,
    staticExtradata: BytesLike,
    maximumFill: BigNumberish,
    listingTime: BigNumberish,
    expirationTime: BigNumberish,
    salt: BigNumberish,
    orderbookInclusionDesired: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  approved(
    arg0: string,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  atomicMatch_(
    uints: BigNumberish[],
    staticSelectors: [BytesLike, BytesLike],
    firstExtradata: BytesLike,
    firstCalldata: BytesLike,
    secondExtradata: BytesLike,
    secondCalldata: BytesLike,
    howToCalls: [BigNumberish, BigNumberish],
    metadata: BytesLike,
    signatures: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  codename(overrides?: CallOverrides): Promise<string>;

  defaultProtocolFee(
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { fee: BigNumber; target: string }>;

  feeAggregator(overrides?: CallOverrides): Promise<string>;

  fills(
    arg0: string,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  hashOrder_(
    registry: string,
    maker: string,
    staticTarget: string,
    staticSelector: BytesLike,
    staticExtradata: BytesLike,
    maximumFill: BigNumberish,
    listingTime: BigNumberish,
    expirationTime: BigNumberish,
    salt: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  initOwner(
    _owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    registryAddrs: string[],
    protocolFeeReceiver: string,
    _feeAggregator: string,
    _royaltiesRegistry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  protocolFeeReceivers(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { fee: BigNumber; target: string }>;

  psiFee(
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { fee: BigNumber; target: string }>;

  registries(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  royaltiesRegistry(overrides?: CallOverrides): Promise<string>;

  setDefaultProtocolFee(
    protocolFee: BigNumberish,
    protocolFeeReceiver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOrderFill_(
    hash_: BytesLike,
    fill: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setProtocolFeeForToken(
    token: string,
    protocolFee: BigNumberish,
    protocolFeeReceiver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRegistry(
    registryAddrs: string,
    enabled: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRoyaltiesRegistry(
    newRoyaltiesRegistry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferWithFees(
    registry: string,
    from: string,
    to: string,
    asset: LibAsset.AssetStruct,
    counterAsset: LibAsset.AssetStruct,
    assetExtraData: BytesLike,
    arg6: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validateOrderAuthorization_(
    hash_: BytesLike,
    maker: string,
    signature: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  validateOrderParameters_(
    registry: string,
    maker: string,
    staticTarget: string,
    staticSelector: BytesLike,
    staticExtradata: BytesLike,
    maximumFill: BigNumberish,
    listingTime: BigNumberish,
    expirationTime: BigNumberish,
    salt: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    EIP_1271_MAGICVALUE(overrides?: CallOverrides): Promise<string>;

    approveOrderHash_(
      hash_: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    approveOrder_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      orderbookInclusionDesired: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    approved(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    atomicMatch_(
      uints: BigNumberish[],
      staticSelectors: [BytesLike, BytesLike],
      firstExtradata: BytesLike,
      firstCalldata: BytesLike,
      secondExtradata: BytesLike,
      secondCalldata: BytesLike,
      howToCalls: [BigNumberish, BigNumberish],
      metadata: BytesLike,
      signatures: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    codename(overrides?: CallOverrides): Promise<string>;

    defaultProtocolFee(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { fee: BigNumber; target: string }>;

    feeAggregator(overrides?: CallOverrides): Promise<string>;

    fills(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashOrder_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    initOwner(_owner: string, overrides?: CallOverrides): Promise<void>;

    initialize(
      registryAddrs: string[],
      protocolFeeReceiver: string,
      _feeAggregator: string,
      _royaltiesRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    name(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    protocolFeeReceivers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { fee: BigNumber; target: string }>;

    psiFee(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { fee: BigNumber; target: string }>;

    registries(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    royaltiesRegistry(overrides?: CallOverrides): Promise<string>;

    setDefaultProtocolFee(
      protocolFee: BigNumberish,
      protocolFeeReceiver: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setOrderFill_(
      hash_: BytesLike,
      fill: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFeeForToken(
      token: string,
      protocolFee: BigNumberish,
      protocolFeeReceiver: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setRegistry(
      registryAddrs: string,
      enabled: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setRoyaltiesRegistry(
      newRoyaltiesRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferWithFees(
      registry: string,
      from: string,
      to: string,
      asset: LibAsset.AssetStruct,
      counterAsset: LibAsset.AssetStruct,
      assetExtraData: BytesLike,
      arg6: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    validateOrderAuthorization_(
      hash_: BytesLike,
      maker: string,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    validateOrderParameters_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "OrderApproved(bytes32,address,address,address,bytes4,bytes,uint256,uint256,uint256,uint256,bool)"(
      hash?: BytesLike | null,
      registry?: null,
      maker?: string | null,
      staticTarget?: null,
      staticSelector?: null,
      staticExtradata?: null,
      maximumFill?: null,
      listingTime?: null,
      expirationTime?: null,
      salt?: null,
      orderbookInclusionDesired?: null
    ): OrderApprovedEventFilter;
    OrderApproved(
      hash?: BytesLike | null,
      registry?: null,
      maker?: string | null,
      staticTarget?: null,
      staticSelector?: null,
      staticExtradata?: null,
      maximumFill?: null,
      listingTime?: null,
      expirationTime?: null,
      salt?: null,
      orderbookInclusionDesired?: null
    ): OrderApprovedEventFilter;

    "OrderFillChanged(bytes32,address,uint256)"(
      hash?: BytesLike | null,
      maker?: string | null,
      newFill?: null
    ): OrderFillChangedEventFilter;
    OrderFillChanged(
      hash?: BytesLike | null,
      maker?: string | null,
      newFill?: null
    ): OrderFillChangedEventFilter;

    "OrdersMatched(bytes32,bytes32,address,address,uint256,uint256,bytes32)"(
      firstHash?: null,
      secondHash?: null,
      firstMaker?: string | null,
      secondMaker?: string | null,
      newFirstFill?: null,
      newSecondFill?: null,
      metadata?: BytesLike | null
    ): OrdersMatchedEventFilter;
    OrdersMatched(
      firstHash?: null,
      secondHash?: null,
      firstMaker?: string | null,
      secondMaker?: string | null,
      newFirstFill?: null,
      newSecondFill?: null,
      metadata?: BytesLike | null
    ): OrdersMatchedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "Transfer(tuple,address,address,bytes4,bytes)"(
      asset?: null,
      from?: null,
      to?: null,
      transferType?: null,
      assetExtraData?: null
    ): TransferEventFilter;
    Transfer(
      asset?: null,
      from?: null,
      to?: null,
      transferType?: null,
      assetExtraData?: null
    ): TransferEventFilter;
  };

  estimateGas: {
    EIP_1271_MAGICVALUE(overrides?: CallOverrides): Promise<BigNumber>;

    approveOrderHash_(
      hash_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    approveOrder_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      orderbookInclusionDesired: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    approved(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    atomicMatch_(
      uints: BigNumberish[],
      staticSelectors: [BytesLike, BytesLike],
      firstExtradata: BytesLike,
      firstCalldata: BytesLike,
      secondExtradata: BytesLike,
      secondCalldata: BytesLike,
      howToCalls: [BigNumberish, BigNumberish],
      metadata: BytesLike,
      signatures: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    codename(overrides?: CallOverrides): Promise<BigNumber>;

    defaultProtocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    feeAggregator(overrides?: CallOverrides): Promise<BigNumber>;

    fills(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashOrder_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initOwner(
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      registryAddrs: string[],
      protocolFeeReceiver: string,
      _feeAggregator: string,
      _royaltiesRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeReceivers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    psiFee(overrides?: CallOverrides): Promise<BigNumber>;

    registries(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    royaltiesRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    setDefaultProtocolFee(
      protocolFee: BigNumberish,
      protocolFeeReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOrderFill_(
      hash_: BytesLike,
      fill: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setProtocolFeeForToken(
      token: string,
      protocolFee: BigNumberish,
      protocolFeeReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRegistry(
      registryAddrs: string,
      enabled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRoyaltiesRegistry(
      newRoyaltiesRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferWithFees(
      registry: string,
      from: string,
      to: string,
      asset: LibAsset.AssetStruct,
      counterAsset: LibAsset.AssetStruct,
      assetExtraData: BytesLike,
      arg6: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validateOrderAuthorization_(
      hash_: BytesLike,
      maker: string,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateOrderParameters_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    EIP_1271_MAGICVALUE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approveOrderHash_(
      hash_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    approveOrder_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      orderbookInclusionDesired: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    approved(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    atomicMatch_(
      uints: BigNumberish[],
      staticSelectors: [BytesLike, BytesLike],
      firstExtradata: BytesLike,
      firstCalldata: BytesLike,
      secondExtradata: BytesLike,
      secondCalldata: BytesLike,
      howToCalls: [BigNumberish, BigNumberish],
      metadata: BytesLike,
      signatures: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    codename(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    defaultProtocolFee(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    feeAggregator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fills(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashOrder_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initOwner(
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      registryAddrs: string[],
      protocolFeeReceiver: string,
      _feeAggregator: string,
      _royaltiesRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeReceivers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    psiFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registries(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    royaltiesRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDefaultProtocolFee(
      protocolFee: BigNumberish,
      protocolFeeReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOrderFill_(
      hash_: BytesLike,
      fill: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFeeForToken(
      token: string,
      protocolFee: BigNumberish,
      protocolFeeReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRegistry(
      registryAddrs: string,
      enabled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRoyaltiesRegistry(
      newRoyaltiesRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferWithFees(
      registry: string,
      from: string,
      to: string,
      asset: LibAsset.AssetStruct,
      counterAsset: LibAsset.AssetStruct,
      assetExtraData: BytesLike,
      arg6: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validateOrderAuthorization_(
      hash_: BytesLike,
      maker: string,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateOrderParameters_(
      registry: string,
      maker: string,
      staticTarget: string,
      staticSelector: BytesLike,
      staticExtradata: BytesLike,
      maximumFill: BigNumberish,
      listingTime: BigNumberish,
      expirationTime: BigNumberish,
      salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
