/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  NaaSAtomicizer,
  NaaSAtomicizerInterface,
} from "../NaaSAtomicizer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "addrs",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "values",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "calldataLengths",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "calldatas",
        type: "bytes",
      },
    ],
    name: "atomicize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class NaaSAtomicizer__factory {
  static readonly abi = _abi;
  static createInterface(): NaaSAtomicizerInterface {
    return new utils.Interface(_abi) as NaaSAtomicizerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NaaSAtomicizer {
    return new Contract(address, _abi, signerOrProvider) as NaaSAtomicizer;
  }
}
