name: OMNI Marketplace Frontend Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  CI: false
  NODE_VERSION: '16.x'
  REACT_APP_CHAIN_ID: "56"
  REACT_APP_PSI_API_URL: "https://psi-api.azurewebsites.net/api"
  REACT_APP_PSI_API_NFT_URL: "https://psi-nft-api.azurewebsites.net/api"
  REACT_APP_PASSBASE_API_KEY: "egDVUwfuac5lyM0eTVXgoSIScKWb7ESikDynO3lXNXM4Lo7KHMznWLlc6pjteK1U"
  REACT_APP_GOOGLE_ANALYTICS_ID: "G-EWZN5J1CTX"

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: yarn

      - name: Install
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_FIELD_0C9C0F003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          skip_app_build: true
          app_location: "/build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_FIELD_0C9C0F003 }}
          action: "close"
